name = "simple-fastmcp-server"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["rpc"]

[env.production]
name = "simple-fastmcp-server"

[env.staging]
name = "simple-fastmcp-server-staging"

# Optional: Add environment variables
# [vars]
# API_KEY = "your-api-key"

# Optional: Add bindings for storage
# [[kv_namespaces]]
# binding = "MCP_STORE"
# id = "your-kv-namespace-id"

# [[d1_databases]]
# binding = "DB"
# database_name = "mcp-database"
# database_id = "your-database-id"
