name = "fastmcpbasicsimple"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[env.production]
name = "simple-mcp-server"

[env.staging]
name = "simple-mcp-server-staging"

# Optional: Add environment variables
# [vars]
# API_KEY = "your-api-key"

# Optional: Add bindings for storage if needed later
# [[kv_namespaces]]
# binding = "MCP_STORE"
# id = "your-kv-namespace-id"